services:
  db:
    image: mysql:latest
    container_name: mysql
    restart: always
    command: --max_allowed_packet=128M 
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "database"
    ports:
      - "3306:3306"

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
