services:
  db:
    image: mysql:latest
    container_name: mysql
    restart: always
    command: --sql-mode="NO_ENGINE_SUBSTITUTION"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "database"
    ports:
      - "3306:3306"
    volumes:
      - ./build/package/peekadee/dump:/docker-entrypoint-initdb.d

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
